### ISSUE TITLE
Treffen 02.08.16

### ISSUE THREAD

**Issue by kreativmonkey** [FreifunkMYK/PW-Freifunk-Starter#42]
- [x] Node löschen (siehe #31)
- [x] Node editieren (siehe #31)
- [ ] Statische IPs: löschen (siehe #44)
- [ ] Statische IPs: MAC ändern (siehe #44)
- [ ] Kontaktformular inkl. Links
  Links auf Startseite und co. (siehe #64)
- [ ] Mitmachen Bereich anpassen
  Backbone: Überlassungserklärung und \" \"
- [ ] Links von Settingsseite importieren
- [x] Link registrie.freifunk-myk.de umleiten (siehe #47)
